# Generated by Django 3.0.4 on 2020-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='posts',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
