# Generated by Django 3.0.4 on 2020-03-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='AdharNumber',
            field=models.IntegerField(default=None),
        ),
    ]
