# Generated by Django 3.0.4 on 2020-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_adharnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AdharNumber',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
