# Generated by Django 3.0.4 on 2020-03-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200324_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AdharNumber',
            field=models.IntegerField(blank=True, default=None, unique=True),
        ),
    ]
